### PR TITLE
This fix's horizontal scroll on open-source page as per issue #124

### PR DESCRIPTION
**Pull request by vanoop729**
There was a horizontal scroll on the "Open Source" page in mobile view.  Fixed issue #124

### CODE REVIEW

**Comment by vanoop729** [comment]
Hey, @ashutosh1919 I have raised a PR for #124 .  Please review!

**Comment by ashutosh1919** [comment]
@vanoop729 , please sync code in this PR with the present code of the repository.

**Comment by dhruvkrishnavaid** [comment]
@vanoop729 Please add ```overflow-x: hidden``` to body and html. That would leave no chance for the page to scroll horizontally. 🙃

**Comment by vanoop729** [comment]
Hey @ashutosh1919 I have synced it as you asked!

**Comment by saiteja13427** [comment]
@vanoop729 Looks good to me!

Checked the deploy preview and seems like the horizontal scroll issue is fixed with this.

Thus merging this PR!

**Comment by saiteja13427** [comment]
@all-contributors please add @vanoop729 for code

**Pull request merged**
