### PR TITLE
Allow to use images instead of icons for skills

### PR DESCRIPTION
**Pull request by dminkovski**
https://github.com/ashutosh1919/masterPortfolio/issues/33

@saiteja13427 thank you for your trust.
So here is one approach I have come up with - that basically renders an image if you provide the imageSrc property or the icon.
What do you think about this solution?Please let me know if you want me to change and or update stuff 😄

### CODE REVIEW

**Comment by dminkovski** [comment]
I have also noticed that there are not many unit tests present - do you want to add them at some point? We might need to update some dependencies to get testing libraries in there.

**Comment by ashutosh1919** [comment]
@dminkovski please add this image in `portfolio.js` so that we can see it in the deploy preview.

**Comment by saiteja13427** [comment]
@dminkovski The approach looks, good man. I have tested it locally and seems to work perfectly. Here is a screenshot 

image

But as @ashutosh1919 said add one sample to portfolio.js so that we can see in deploy preview as well and users can also have that as reference.

Also, correct the third point (spelling errors) in README.md to `Remove the fontAwesomeClassName property or leave it empty because it takes precedence over imageSrc`

**Comment by dminkovski** [comment]
Thank you @ashutosh1919  & @saiteja13427  for your feedback! I updated and changed the PR 😄 
Please let me know if this suits you! 👍

**Comment by saiteja13427** [comment]
@dminkovski This looks quite good to me. Thanks for it.

@ashutosh1919 do check it once, if you don't have any further comments then we are good to go for a merge.

**Comment by ashutosh1919** [comment]
@all-contributors please add ideas, code

**Comment by ashutosh1919** [comment]
@all-contributors please add @dminkovski  for ideas, code

**Pull request merged**
