### PR TITLE
Add 404 page

### PR DESCRIPTION
**Pull request by abdslam01**

### CODE REVIEW

**Comment by ashutosh1919** [comment]
@abdslam01 , Good work. Attaching the screenshot. As of now, there are multiple text fields overlapping each other. Please fix that and we are good to merge.

Screen Shot 2021-09-14 at 7 23 03 AM

**Comment by abdslam01** [comment]
I tested now, it seems to be okey!

404_ui

**Comment by ashutosh1919** [comment]
@abdslam01 , Can you please revert the version of dependencies to avoid failure?

**Comment by ashutosh1919** [comment]
@abdslam01 , breaks again.
Screen Shot 2021-09-15 at 9 30 01 AM

**Comment by abdslam01** [comment]
i revert the last commit that delete the padding!
@ashutosh1919 it should be okey now!, please check it out

**Comment by ashutosh1919** [comment]
@abdslam01 Thank you so much for contributing. We appreciate it. Keep contributing more.

**Comment by ashutosh1919** [comment]
@add-contributors please add @abdslam01 for code

**Comment by ashutosh1919** [comment]
@all-contributors please add @abdslam01 for code

**Pull request merged**
