### PR TITLE
Organizations list styling

### PR DESCRIPTION
**Pull request by larbisahli**
Suggesting a style on organizations list component by adding transition and styling tooltip.

### CODE REVIEW

**Comment by ashutosh1919** [comment]
@larbisahli , please rebase the branch in order to run the netlify deployment.

**Comment by larbisahli** [comment]
i did, if there is still an issue please correct me and tell me how to fix it.

**Comment by ashutosh1919** [comment]
@larbisahli , It is not yet in sync.Do like this: https://stackoverflow.com/a/12093311

**Comment by larbisahli** [comment]
i did that.

**Comment by larbisahli** [comment]
@ashutosh1919 Thank you for your guidance i appreciate it.

**Comment by ashutosh1919** [comment]
> i did that.

If you did that, then I am not able to see the commit.

**Comment by saiteja13427** [comment]
Closing this branch due to inactivity!

@larbisahli feel free to raise a new PR with only related changes so that we don't have any conflicts and also we can have a deploy preview.

**Pull request closed without merging**
