### PR TITLE
Auto formatting

### PR DESCRIPTION
**Pull request by larbisahli**
adding auto formatting action

### CODE REVIEW

**Comment by ashutosh1919** [comment]
@larbisahli , Good work. Can you please revert the changes other than the workflow dir

**Comment by larbisahli** [comment]
@ashutosh1919 , sure can you tell me how i am still a bit new to git

**Comment by larbisahli** [comment]
@ashutosh1919 ,sure.

**Comment by larbisahli** [comment]
@ashutosh1919  can you please show me how to do it i am a new to git.

**Comment by ashutosh1919** [comment]
@larbisahli, close this PR. Raise a fresh PR. Edit changes only in workflow dir. Then just add the autoformatting yml file in git as shown below.

```
$ git add autoformatting-action.yml
$ git commit -m 'Type message here'
$ git push origin <branch-name>
```

**Comment by larbisahli** [comment]
I closed all PRs

**Comment by larbisahli** [comment]
Did I misunderstood revert changes in the last PR to all changes other 4
PR? If yes tell me please to raise the other PR again sorry about that.

**Pull request closed without merging**
