### PR TITLE
Code refactoring

### PR DESCRIPTION
**Pull request by dhruvkrishnavaid**
- Fixed inconsistent text alignment in header
- Fixed console errors (no key provided by rendering methods and invalid DOM properties).

### CODE REVIEW

**Comment by dhruvkrishnavaid** [comment]
- Updated fontawesome to 6.1.1 and iconify to 2.2.1
- Removed `canvasjs` and `animejs` because they were unused
- Removed `<title>` tag from SVG components because they are of no use
- Removed `xmlns` from all SVG components because they are ignored in inline SVGs

**Comment by dhruvkrishnavaid** [comment]
@ashutosh1919 In the last commit, I had updated `react-scripts` to `5.0.1`. 
This causes the build to fail on older versions of Node.js
I request you to please update the Node.js CI to use 14.x or the latest 16.x for build.

**Comment by saiteja13427** [comment]
@dhruvkrishnavaid why do we have these many changes, also I see a commit regarding preact and all which you did not mention in the comments.

This is too big PR and is very difficult to review.

Can you divide it and raise smaller PRs, please.

**Comment by dhruvkrishnavaid** [comment]
@saiteja13427 The commits related to Preact were mentioned in my old PR (#172) and were reverted in commits [`ed4c8e9`](https://github.com/ashutosh1919/masterPortfolio/pull/219/commits/ed4c8e9681414da9421546d665cb9193bf643f91) and [`ae9daff`](https://github.com/ashutosh1919/masterPortfolio/pull/219/commits/ae9daff59ee4a78909e3bcb0fafb2ee0f22b74ec). They can be safely ignored.

**Comment by saiteja13427** [comment]
@dhruvkrishnavaid Alright, but still this is too big of a PR. Please divide it and raise smaller PRs.

**Comment by dhruvkrishnavaid** [comment]
Most of the files listed in the *Files changed* section are the updated font-awesome assets located at [`src/assets/font-awesome`](https://github.com/ashutosh1919/masterPortfolio/tree/master/src/assests/font-awesome). You can filter them or scroll past through them. Or it would be much easier to review changes in every commit separately.

**Comment by dhruvkrishnavaid** [comment]
> @dhruvkrishnavaid Alright, but still this is too big of a PR. Please divide it and raise smaller PRs.

Ok, I'll raise separate PRs with smaller changes.

**Comment by saiteja13427** [comment]
Thanks man @dhruvkrishnavaid

**Pull request closed without merging**
