### PR TITLE
Empty fields

### PR DESCRIPTION
**Pull request by aash1999**
Many developers don't have publications or certifications. So I fixed certifications.certifications.length ==0 and publications.data.length == 0 edge case.

### CODE REVIEW

**Comment by saiteja13427** [comment]
Thanks for reporting and raising this issue @aash1999.

This looks good to me!

But seems like you have pushed the package.lock file as well which is unnecessary. Can you just revert that and push.

You can follow this guide to remove the packag. lock file changes: https://dev.to/lofiandcode/git-and-github-how-to-revert-a-single-file-dha

**Comment by saiteja13427** [comment]
@aash1999 I can still see differences in the package.lock file. Can you once check?

**Comment by aash1999** [comment]
@saiteja13427 can I know to which commit id I should revert to ?

**Comment by saiteja13427** [comment]
@aash1999 Seems like the revert you did is to the correct commit only. Don't know why is it not working. 

There are only two differences, can you just manually correct them and push?

**Comment by aash1999** [comment]
@saiteja13427 please check now

**Comment by saiteja13427** [comment]
Seems perfect now.

LGTM. Merging this PR

**Comment by saiteja13427** [comment]
@all-contributors please add @aash1999  for code

**Comment by saiteja13427** [comment]
Thanks a lot for the contribution @aash1999 🥳

Keep contributing!

**Pull request merged**
