### PR TITLE
Fixed h1 in skill section of Home page. #14

### LINKED ISSUE #14: Text overlap on `h1`
image

https://ashutosh1919.github.io/#/home

Latest Chrome MacOS

### PR DESCRIPTION
**Pull request by th3c0d3br34ker**
Hey, @ashutosh1919 I tried to fix the h1 overlapping issue. Please review it.

image

Fixes #14

### CODE REVIEW

**Comment by ashutosh1919** [comment]
@th3c0d3br34ker , Can you please pull the changes and commit your changes again. I have added prettier to autoformat code.

**Comment by larbisahli** [comment]
Reducing font-size from 56px to 52px is a poor solution to the problem.

**Comment by ashutosh1919** [comment]
> Reducing font-size from 56px to 52px is a poor solution to the problem.

@larbisahli , yes I agree. I think the problem here is with line-height and not with font-size. @larbisahli , please feel free to review the code for this PR and suggest changes.

**Comment by larbisahli** [comment]
@ashutosh1919  line-height of 1em is sufficient i made a PR

**Comment by th3c0d3br34ker** [comment]
Thank you @larbisahli , I fixed the line height property, will commit and you can check it

**Comment by th3c0d3br34ker** [comment]
Ahh jeez, what should I do now, with my PR?

**Comment by ashutosh1919** [comment]
@th3c0d3br34ker , please take help from #15

**Comment by ashutosh1919** [comment]
I will be adding both of you as contributor if this PR gets merged. Don't worry for that .

**Comment by th3c0d3br34ker** [comment]
I was aware about line height, since it would look better if the heading text is in one line, so I decreased the font size. However, I will be around looking forward to help people. 😄

**Pull request closed without merging**
