### PR TITLE
Updating Dockerfile

### PR DESCRIPTION
**Pull request by Adamou02**
Some basic fixes 

- Using recent image of NodeJS.

- Removing useless layer in the Dockerfile

- Removing useless instructions and adding EXPOSE

### CODE REVIEW

**Comment by ashutosh1919** [comment]
@Adamou02 Can you please remove changes other than dockerfile from this PR?

**Comment by Adamou02** [comment]
> @Adamou02 Can you please remove changes other than dockerfile from this PR?

Done. "Assests" folder ? Is it the right name ?

**Comment by ashutosh1919** [comment]
@allcontributors please add @Adamou02 for code

**Comment by Adamou02** [comment]
> @Adamou02 Yes we know that it is spell mistake but we can change it in separate PR.

Done (#380]

**Pull request merged**
