### PR TITLE
Fix: multiple console errors 

### PR DESCRIPTION
**Pull request by varundhand**
## Closes issue #333 

# Changes Made:

- Fixed syntax errors
- Resolved semantic issues
- Corrected logical errors

# Screenshots:
## _Before_:
Screenshot 2023-10-25 at 2 03 18 AM

## _After( clear console without any errors ):_
Screenshot 2023-10-25 at 2 47 18 AM

### CODE REVIEW

**Comment by varundhand** [comment]
@ashutosh1919 ready for review :)

**Comment by varundhand** [comment]
@ashutosh1919 ready for review :)

**Comment by ashutosh1919** [comment]
@varundhand please remove svg files from this commit! Those won't change to remove errors right?

**Comment by varundhand** [comment]
Probably not. Let me remove them then.

**Comment by varundhand** [comment]
@ashutosh1919 I have removed the svg files now, you can review it :)

**Review by ashutosh1919 — APPROVED** [review]
LGTM

**Comment by ashutosh1919** [comment]
@allcontributors please add @varundhand for code

**Pull request merged**
