### PR TITLE
Permanent fix for horizontal scroll on opensource page

### PR DESCRIPTION
**Pull request by dhruvkrishnavaid**

### CODE REVIEW

**Comment by ashutosh1919** [comment]
@dhruvkrishnavaid , It hides the part of screen for opensource screen in iPhone 5 screen.

**Comment by dhruvkrishnavaid** [comment]
Now it won't. 😄

**Comment by vanoop729** [comment]
This is exact copy of #125  by @vanoop729

**Comment by ashutosh1919** [comment]
Thanks @vanoop729 for bringing this one to my notice.
@dhruvkrishnavaid , I am closing this PR but suggesting you to add your comments in #125 so that it can be integrated

**Pull request closed without merging**
