### PR TITLE
puppeteer automation project

### PR DESCRIPTION
**Pull request by paramveer1999**
This will help you to get all the possible outcomes  of your desired accommodation automatically according to your need in a screenshot format.

You have to provide following details :

->property type
->Budget
->BHK
->residential-buy,rent

and rest of the things will be done by script automatically.

### CODE REVIEW

**Comment by ashutosh1919** [comment]
@paramveer1999 , please also attach GIF of UI for changed code. Thanks for contribution!

**Comment by paramveer1999** [comment]
> @paramveer1999 , please also attach GIF of UI for changed code. Thanks for contribution!

@ashutosh1999 gif uploaded

**Comment by paramveer1999** [comment]
> @paramveer1999 , please also attach GIF of UI for changed code. Thanks for contribution!

@ashutosh1919  gif uploaded

**Comment by ashutosh1919** [comment]
@paramveer1999 , I think this is not relevant to the project. Closing PR.

**Pull request closed without merging**
