### PR TITLE
Add .env to the Project For Github Token

### PR DESCRIPTION
**Pull request by saiteja13427**
This PR removes the GitHub token and username from the git_data_fetcher.mjs and adds it to a new env file.

### Changes
1. Added an env.example file with token and username which users will have to rename to .env.
2. Added new instructions in README.
3. Added dotenv package as a dev dependency as it is needed to use .env variables.
4. Added .env to gitignore.

This PR addresses #220 

@ashutosh1919 do have a look!

### CODE REVIEW

**Comment by ashutosh1919** [comment]
@saiteja13427 can you please investigate why the build fails?

**Comment by saiteja13427** [comment]
Yes @ashutosh1919 not yet able to understand why is the build failing. Will figure it out and update

**Comment by ashutosh1919** [comment]
@saiteja13427 Also we need to figure out a way to remove the `package-lock.json` file from the repo. Everytime we update a package, it shows huge change in that file.

**Comment by tamojit-123** [comment]
@saiteja13427 & @ashutosh1919 someone with the privileges need to retrigger the builds from GitHub actions. This issue occurs if there are simultaneous PRs and the build is going on simultaneously.

**Comment by saiteja13427** [comment]
@tamojit-123 I have actually tried running the test again back then but that did not work out actually. Will check this again and see.

**Comment by tamojit-123** [comment]
Please refer to this link might help: https://stackoverflow.com/questions/68021121/fsevents-not-accessible-from-jest-haste-map
I did it the same way

**Comment by saiteja13427** [comment]
@tamojit-123 The issue was an incompatibility of the dotenv version actually, I resolved it.

**Comment by saiteja13427** [comment]
@ashutosh1919 Do have a look at this PR

Will merge it once you have a look.

We will have to update our testing npm versions and lock file versions to do updates to packages in future. We can also change our tests from node 10.x 12.x to 14.x and 16.x maybe.

**Review by ashutosh1919 — APPROVED** [review]
LGTM!

**Comment by saiteja13427** [comment]
Alright merging it then!

**Pull request merged**
