### PR TITLE
Fix for #21

### LINKED ISSUE #21: git_data_fetcher.js returns an Error when executed for the second time
`Error occured in pinned projects 2 {}
{}
{}
{}
`

### PR DESCRIPTION
**Pull request by dhruvkrishnavaid**
This PR fixes #21.

### CODE REVIEW

**Comment by NirmalSilwal** [comment]
One thing I would like to ask more, in my case, **all the organization are not displayed where I contributed** but I can see the activity (PR or issue) in the list.

Why might have that happened? It is only displaying few org but I have contributed to other org also. So I was wondering if that org list is filtered by particular time frame of contribution or anything else? 

 Attaching screenshot for reference - 

Capture

**Comment by dhruvkrishnavaid** [comment]
> @dhruvkrishnavaid , Can you please write a little bit about what you fixed and how it will solve the problem? I need to understand a bit. Also, it would help a fix get logged. Thanks for contribution

First,  file extension has been changed from '.js' to '.mjs'. This has been done because node recognised the earlier `git_data_fetcher.js` as a CommonJS file (because it's Node's default module system). But CommonJS uses require imports and module.exports and `require('dotenv')` isn't supported because it's a ES6 module (I'll soon add dotenv support in this PR). 
And second, the readme has been updated, because, JS code was wrongly indicated as Python code in it. This lead to wrong syntax highlighting. This has been fixed.

**Comment by dhruvkrishnavaid** [comment]
> in this section we directly added the github token but that is not secure way to add tokens. What is the potential solution for this?

@NirmalSilwal  It can be done using dotenv. See #102.

**Comment by ashutosh1919** [comment]
@dhruvkrishnavaid , Thanks so much for contribution. Appreciate it.

**Pull request merged**
