### PR TITLE
Ian Credit & Visual Logo

### PR DESCRIPTION
**Pull request by mrjatinchauhan**
Hope this would give viewers proper description of credits. So that further #40  issue won't be raised.

### CODE REVIEW

**Comment by mrjatinchauhan** [comment]
Just proposed changes for readme.md as access is been denies. 
You can make changes to readme for credit of Ian Storm by linking to his github profile. Which should stop issues like #40 as proper credit been given.

**Comment by ashutosh1919** [comment]
Please resolve conflicts and synchronise repo. https://stackoverflow.com/a/12093311/8289194

**Comment by ashutosh1919** [comment]
Please resolve merge conflicts. Also remove changes in package-lock.json

**Comment by mrjatinchauhan** [comment]
resolves @ #60

**Pull request closed without merging**
