### PR TITLE
add json schemaorg

### PR DESCRIPTION
**Pull request by cdigruttola**

### CODE REVIEW

**Comment by ashutosh1919** [comment]
@cdigruttola I have no clue about schemaorg and why is it used? Can you add couple of lines of descriptions about schemaorg which can be used as a reference for its usage?

Also, why does it show that the commit is not signed.

**Comment by cdigruttola** [comment]
Hi, 

"Person" is used to create a semantic correlation between entity the name (eg. Ashutosh Hathidara) and all  info about (eg. work, email, photo, homepage, etc). It used by Google to correctly define the entity. Here an exmaple for worpdress https://wpschema.com/docs/add-schema-markup-for-a-person/

The commits aren't signed to to my forgetfulness during commit.

Carmine

**Comment by ashutosh1919** [comment]
@cdigruttola Thank you for contributing. It will really help the project

**Comment by ashutosh1919** [comment]
@allcontributors please add @cdigruttola for ideas, promotion

**Pull request merged**
