### PR TITLE
Code refactoring and addressing other issues

### PR DESCRIPTION
**Pull request by dhruvkrishnavaid**
Earlier, when navigation items were center aligned in the *Projects* page and left aligned in all other pages. This PR fixes this issue by explicitly adding `text-align: center;` to header links.

### CODE REVIEW

**Comment by dhruvkrishnavaid** [comment]
@saiteja13427 Please review this PR

**Comment by dhruvkrishnavaid** [comment]
- Added `defer` to fontawesome and iconify for better performance
- Removed `canvasjs` and `animejs` because they were unused

**Comment by dhruvkrishnavaid** [comment]
- Add fetch script to `package.json` (Now run `npm fetch` instead of `node git_data_fetcher.mjs`)

**Comment by saiteja13427** [comment]
@dhruvkrishnavaid 

1. Please remove the package-lock.json as it's not required I think
2. Also we are discussing to give some options while running the GitHub script. Thus we wouldn't want to add script in package json. Please revert those changes and we will be good to go.

**Comment by dhruvkrishnavaid** [comment]
The current package-lock.json was created using an older version of npm.
This one just adds an automatically generated compatibility layer for latest versions of npm.

And, I'll remove the fetch script from package.json in my next commit.

**Comment by dhruvkrishnavaid** [comment]
@ashutosh1919 What is your opinion on this?

**Comment by dhruvkrishnavaid** [comment]
This commit addresses #220. 
- Added `dotenv`
- Updated `react-scripts` to the latest version to get benefit from latest performance and security fixes in `create-react-app`

NOTE: Updating `react-scripts` means that this project will no longer successfully build on Node.js versions prior to `v12.2.0`, hence updated the version of Node.js CI.

**Comment by dhruvkrishnavaid** [comment]
I've added only the token to `.env`, so the username will still be hardcoded. This is because I remember facing some issue where Node could not successfully fetch the data because it was unable to read the username.

This should not be a matter of concern because our GitHub username is already public ;)

**Comment by dhruvkrishnavaid** [comment]
@ashutosh1919 Your opinion is awaited :octocat:

**Comment by ashutosh1919** [comment]
@dhruvkrishnavaid please remove changes in `package-lock.json`

**Comment by dhruvkrishnavaid** [comment]
I've reverted the changes in `package-lock.json`.
The current changes are because of addition of `dotenv` and the upgrade of `react-scripts` to version `5.0.1`.
These changes are necessary else the CI build will fail due to improper sync of `package.json` and `package-lock.json`.

**Comment by dhruvkrishnavaid** [comment]
I've used npm version `6.14.17`, which is the version Node.js 14.x CI uses, to generate the current lockfile, to make sure this does not cause any issue :)

**Pull request closed without merging**
