### PR TITLE
fixed -  horizontal scrollbar on animation time along with each page

### PR DESCRIPTION
**Pull request by SandipDhang**
Heyy..! I just loved your design. I also going to use this design (mainly the SVGs) for my own portfolio but after customising it on my way. I found a issue on your project ("Horizontal scrollbar") which I've fixed and PR is created.I'm a fresher web technology started career as a Frontend developer in React so please review this and merge it it will help me to grow my confidence. Thanks

### CODE REVIEW

**Comment by ashutosh1919** [comment]
@all-contributors please add @SandipDhang for code

**Comment by ashutosh1919** [comment]
@SandipDhang , thanks for the contribution. Keep contributing to project.

**Comment by SandipDhang** [comment]
@ashutosh1919 Thanks buddy. Can you please close the issue also from the issue tab it's still in open status

**Comment by ashutosh1919** [comment]
@SandipDhang Can you please mention the issue number here?

**Pull request merged**
